black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 153
  - 104
  min:
  - 97
  - 122
  - 50
green:
  max:
  - 255
  - 128
  - 156
  min:
  - 0
  - 105
  - 125
red:
  max:
  - 255
  - 170
  - 145
  min:
  - 0
  - 130
  - 115
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
yellow:
  max:
  - 255
  - 128
  - 185
  min:
  - 150
  - 105
  - 158
