black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 153
  - 104
  min:
  - 97
  - 122
  - 50
green:
  max:
  - 224
  - 104
  - 255
  min:
  - 50
  - 0
  - 143
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 178
  - 117
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
yellow:
  max:
  - 255
  - 255
  - 255
  min:
  - 47
  - 141
  - 0
